#!/bin/bash

cd files


lower_alpabet=(a b c d e f g h i j k l m n o p q r s t u v w x y z)
upper_alpabet=(A B C D E F G H I J K L M N O P Q R S T U V W X Y Z)

shopt -s nullglob
for i in ${!lower_alpabet[@]}; do

mv ${lower_alpabet[i]}* /home/workspace/SWE_2021_41_2023_2_week_4-main/${lower_alpabet[i]}
mv ${upper_alpabet[i]}* /home/workspace/SWE_2021_41_2023_2_week_4-main/${upper_alpabet[i]}

done